name: Build

env:
  # The name of the main module repository
  main_project_module: app
  
  main_project_name: native-activity
  # The name of the Play Store
  playstore_name: Frogobox ID

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    
      - id: upload
        uses: ./.github/actions/upload_build
        if: ${{steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: ./${{ env.main_project_module }}/build/outputs/apk/${{ env.main_project_module }}-debug.apk
          DEST_NAME: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
      
      - uses: actions/checkout@v4
      # Set Current Date As Env Variable
      - run: |
          echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV 
          
          echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        id: compile
        with:
             distribution: 'zulu' # See 'Supported distributions' for available options
             java-version: '17'
             cache: 'gradle'

      - run: |
         chmod +x ./gradlew

         ./gradlew build
        
         ./gradlew assembleDebug
         
      - uses: ./.github/actions/notify_failure
        if: ${{steps.compile.outcome == 'failure'}}
        with:
          NOTIFY_MESSAGE: 'Failed to compile app! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
      
      - uses: ./.github/actions/notify_success
        if: ${{steps.compile.outcome == 'success'}}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled app.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'

      - uses: ./.github/actions/notify_failure
        if: ${{steps.upload.outcome == 'failure'}}
        with:
          NOTIFY_MESSAGE: 'Failed to upload app.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
