name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app
  
  main_project_name: native-activity
  # The name of the Play Store
  playstore_name: Frogobox ID

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build
        
      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        id: compile
        run: ./gradlew assembleDebug
        
      - name: Notify of failure
        uses: ./.github/actions/notify_failure
        if: ${{steps.compile.outcome == 'failure'}}
        with:
          NOTIFY_MESSAGE: 'Failed to compile app! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload Build
        uses: ./.github/actions/upload_build
        id: upload
        with:
          SOURCE_FILE: ./${{ env.main_project_module }}/build/outputs/apk/${{ env.main_project_module }}-debug.apk
          DEST_NAME: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
      - name: Notify of success           
        uses: ./.github/actions/notify_success
        if: ${{steps.compile.outcome == 'success'}}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled app.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
      - name: Notify of upload failure 
        uses: ./.github/actions/notify_failure
        if: ${{steps.upload.outcome == 'failure'}}
        with:
          NOTIFY_MESSAGE: 'Failed to upload build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
